### ISSUE TITLE
css is not present?

### ISSUE THREAD

**Issue by DE-co-DE** [vacarsu/uikit-react#32]
I installed it using npm and imported in my component

`import { List,ListItem,Badge} from 'uikit-react';`

and after compilation i can see classes in DOM but thier css is missing?
am i missing something or its a bug?

**Comment by AyoubGhaddab** [comment]
i have the same probleme, did you fix it @DE-co-DE  ?

**Comment by DE-co-DE** [comment]
> i have the same probleme, did you fix it @DE-co-DE ?

Nopes , No Luck ..
