### ISSUE TITLE
modal was not found !!

### ISSUE THREAD

**Issue by larbibaraka** [vacarsu/uikit-react#34]
hello i was searching for modal but i think its not implemented yet maybe can you confirme thanks

**Comment by vacarsu** [comment]
Modal has not been implemented yet, however you can still use the default uikit modal along side this library.

**Comment by larbibaraka** [comment]
yes thanks i did that :)

**Comment by JesusTheHun** [comment]
Hi, any chance you can add it soon ?
Do you still maintain this repo ? PR still accepted ?

**Comment by vacarsu** [comment]
@JesusTheHun I can find some time to work on this throughout the week. I do still maintain this repo just have not had a whole lot of time in the last while. I do accept PRs too.

**Comment by wolfcreative** [comment]
Please add the "modal". It is he who is sorely lacking :<
