### ISSUE TITLE
Still getting jest conflict after PR #37 was merged.

### ISSUE THREAD

**Issue by danieljustus32** [vacarsu/uikit-react#38]
Hi, when installing uikit-react, I'm still getting the error about conflicting jest versions. Looks like the uikit-react package.json that I'm pulling down is the same as it was before you merged that PR. Steps I've taken:

1) Deleted node_modules and yarn.lock
2) Double-checked I'm requiring uikit-react v3.0.20 in my package.json
3) Reinstalled dependencies

Uikit-react still appears to be installing jest@23.6.0 though. Is it something I'm doing? Thanks for taking a look!

**Comment by danieljustus32** [comment]
FYI, I got it fixed by running `yarn add https://github.com/vacarsu/uikit-react.git`

**Comment by vacarsu** [comment]
This should be resolved now with the most recent updates I made.
